### ISSUE TITLE
Block Image Slider does not display any images anymore

### ISSUE THREAD

**Issue by Tcoton** [thirtybees/homeslider#10] opened 2024-02-08 21:47 UTC
After updating thirty bees to version 1.5 and up, the module does not display images anymore.
 I have tried to load PNG and JPG files of different sizes without success.
I have uninstalled and reinstalled the module, the default pictures do not display either.
I have tried with Safari, Firefox, Edge, none of them display any picture in the module whether on Apple computer, PC computer or tablet.

The titles are displayed, the button "shop now" is displayed, the link to the image is working but there is no image apart the "missing picture" one.

**Comment by getdatakick** [comment] 2024-02-09 07:12
Closing as duplicate of issue #7

You will have to modify your theme override template

**Closed as completed by getdatakick** 2024-02-09 07:12 UTC
