### ISSUE TITLE
Deletes existing image slides

### ISSUE THREAD

**Issue by obewanz** [thirtybees/homeslider#9] opened 2023-10-29 00:18 UTC
Upon upgrade from 2.0.5 the slider images did not display within the module slide configuration or list panels, they do however still display on the front end. You CAN restore the display by RE-UPLOADING the images, but I should NOT have to do that after a module "UPDATE"! 

THIS IS EXACTLY WHY I HATE BEING "PUSHED" TO DO THESE MODULE UPGRADES - SOMETHING ALWAYS GETS BROKEN - ALWAYS!!!

**Comment by obewanz** [comment] 2023-10-29 00:23
Oh Joy! Now I just discovered after "uploading" the image files - THEY DO NOT DISPLAY! I get the No Image Image. :'/

**Comment by obewanz** [comment] 2023-10-29 01:38
uninstalled and reuploaded original 2.0.5 version and no joy, so I deleted the module files in both the module folder and the theme/module folder and then uploaded files from a recent local backup, still no joy. So I "reset" the module, and while that did not immediately fix the problem because obviously all of my settings were overwritten - I did restore the tb_homeslider_slides_lang table (since I only ever replaced the slides that were part of the install of the module). <-- THIS finally got things back to the way they were, minus the module hook changes. I had a similar problem with the themeconfigurator module so I used the same process to restore it - now both modules are functioning again on the site as they were before - BUT THIS JUST REINFORCES the need for a ROLLBACK or some other mechanism to ensure stuff doesn't get broken with these updates. This also very succinctly illustrates why once I get a shop up and running - I RARELY do any updates unless I have done them repeatedly and successfully each time on the beta/dev site for the production site that is to be updated. This takes a long time, but I wasted an hour and a half running this issue down just to get back to where I was before - at least on the beta/dev I can do a whole site restore in a few minutes and start over or just stop trying to do an upgrade. This particular time - I broke these rules and applied directly to a production site - NEVER AGAIN!!

**Comment by getdatakick** [comment] 2023-10-30 08:14
This is duplicate of issues #3 and #8

Version 2.0.5 was released to address this problem. 

The problem was in the update process itself (part of the core) -- update deleted entire module directory, and replace it with fresh module version. Because module stored images inside module directory, they were deleted.

Version 2.0.5 stores images in /img/ directory in store root, not in module. So, update from 2.0.5 to newer version will not delete them.

However, update to 2.0.5 still deletes the images.

**Closed as completed by getdatakick** 2023-10-30 08:14 UTC
Labels: duplicate

**Comment by obewanz** [comment] 2023-10-30 17:16
IF you are going to change storage of slide images to the /img/ directory, instead of slamming module connected images in the root of that directly, why don't you at least put them in a /img/modules/ directory where things can remain more organized??

And if this is the intended behavior of the module upgrade - IT SUX!!! 
As a store owner, I don't expect to have to do ANYTHING after a module upgrade is applied - it should be seamless. As a webmaster/site administrator - I would expect the exact same thing - and going back to your statement above - if you know this is how the "upgrade" affects a website (moving images to a new location without even taking into consideration your own distribution theme (community-theme-default) and WHERE IT looks to retrieve those images - this is just p&$$ poor coding and as usual with ALL of the PS forks/platforms - NO FREAKIN' DOCUMENTATION - EVEN TO WARN PEOPLE!!! of such impacts make for lazy &$$ coding and distribution to boot!

Seriously, if you ever expect me to start tossing money to this project - you'll have to do much better than this!

**Comment by obewanz** [comment] 2023-10-30 17:20
After looking at your reply and investigating my server - I see you at least use the modulename for the directory, but still - following the convention that has been well established, any module that stores images in the site /img/ directory should store said images based on the following structure /img/modules/modulename/. 

One could argue /img/mod/modulename/ would also be consistent with the well established methodology, if you feel the need to minimize the directory structure length.
PS: I see "blockbanner" and "beesblog" do the exact same thing as "homeslider" with regard to the directories. (smh)

**Comment by getdatakick** [comment] 2023-10-31 11:39
noted
